version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    rebase-strategy: auto
    cooldown:
      default-days: 3
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    versioning-strategy: increase-if-necessary
    groups:
      MAJOR-development-dependencies:
        dependency-type: development
        update-types:
          - major
      MAJOR-production-dependencies:
        dependency-type: production
        update-types:
          - major
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "09:30"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    rebase-strategy: auto
    cooldown:
      default-days: 3
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      MAJOR-github-actions:
        patterns:
          - "*"
        update-types:
          - major
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
